
name: (O11) Release Plugin

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      plugin:
        description: 'Name of the plugin in O11'
        required: true
        type: string
jobs:
    deploy:
      name: '🔌 Deploy plugin across LifeTime'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Tag Plugin with Version 
        run: npm run update:version --plugin="${{inputs.plugin}}" --lifetime=${{ secrets.LIFETIME}} --authentication='${{secrets.AUTOMATION_TOKEN}}'

      - name: ⏳ Wait for tag version to propagate
        run: sleep 20  # Waits for 20 seconds

      - name: Deploying from DEV to TST
        run: npm run deploy --plugin="${{inputs.plugin}}" --from=Development --to=Testing --lifetime=${{ secrets.LIFETIME }} --authentication='${{ secrets.AUTOMATION_TOKEN }}'

      - name: ⏳ Wait for deployment to propagate
        run: sleep 20  # Waits for 20 seconds

      - name: Deploying from TST to PROD 
        run: npm run deploy --plugin="${{inputs.plugin}}" --from=Testing --to=Production --lifetime=${{ secrets.LIFETIME }} --authentication='${{ secrets.AUTOMATION_TOKEN }}'
