name: (O11) Update Extensibility

on:
  workflow_call:
    inputs:
      plugin:
        description: 'Name of the plugin in O11'
        required: true
        type: string
      configName:
          description: 'Name to be used in the extensibility configuration of the plugin '
          required: true
          type: string
      tag: 
        description: 'The repo version tag'
        required: true
        type: string
      forgeVersion:
        description: 'The plugin version on the forge'
        required: true
        type: string
      mabsMin:
        description: 'Minimum MABS version'
        required: true
        type: string
      environment:
        description: 'The environment where the plugin resides'
        required: true
        type: string

jobs:    
  update_o11:
    name: '✍🏻 Change O11 Extensibility'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Update Extensibility Configurations JSON
      run: npm run update:tag --plugin=${{ inputs.plugin }} --name='${{ inputs.configName }}' --mabs=${{ inputs.mabsMin }} --environment=${{ inputs.environment }} --repository=${{ github.repository }} --forge=${{ inputs.forgeVersion }} --branch=${{ inputs.tag }} --authentication="${{ secrets.BASICAUTH }}"      

